#!/usr/bin/perl

my $verbose = ($ARGV[0] eq "-v");

my $total = 0;
foreach my $file (<STDIN>)
{
    chomp($file);
    my @st = stat($file);
    my $size_kb = $st[7] / 1024;
    $total += $size_kb;
    if ($verbose)
    { printf("%i: $file\n", $size_kb); }
}

if (!$verbose)
{ printf("%i Mb\n", $total / 1024); }
